version: "3.5"

services:
  adguard-manager:
    container_name: adguard-manager
    image: adguard-manager:latest
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "1080:3000/tcp"
      - "8080:80/tcp"
    environment:
      ADMIN_PASSWORD: "test"
      SPACE_SEPARATED_FILTER_ALLOW: "*.ubuntu.com *.google.com"
      SPACE_SEPARATED_FILTER_DENY: "*.*"
    restart: no
